		var zh = {
			"nav": "OpenCode Go",
			"section.title": "OpenCode Go 设置",
			"key.title": "API 密钥",
			"key.configured": "已配置（存在服务端，不回显）",
			"key.missing": "未配置",
			"key.placeholder": "sk-…",
			"key.save": "保存密钥",
			"key.clear": "清除",
			"key.empty": "请输入密钥",
			"key.saved": "已保存",
			"models.title": "模型",
			"models.refresh": "刷新目录",
			"models.selectAll": "全选",
			"models.selectNone": "全不选",
			"models.ctxPh": "上下文",
			"models.maxPh": "输出上限",
			"models.hint": "点“刷新目录”从服务端拉取可用模型，勾选后才会出现在模型选择器里。",
			"models.surfaces": "三端面（chat / responses / messages）均可用，tag 标注非 chat 模型。",
			"models.enabled": "已选 {count} 个",
			"busy.key": "保存中…",
			"busy.models": "刷新中…",
			"busy.stats": "统计中…",
			"stats.title": "用量统计",
			"stats.tabOverview": "概览",
			"stats.tabModels": "模型",
			"stats.total": "累计",
			"stats.tokens": "tokens",
			"stats.calls": "次调用",
			"stats.colRequests": "请求数",
			"stats.colIO": "输入/输出",
			"stats.colCache": "缓存",
			"stats.refresh": "刷新统计",
			"stats.reset": "清空记录",
			"stats.confirm": "确认清空用量记录吗？当前账本会先归档。",
			"stats.empty": "暂无用量记录，先去聊两句。",
			"stats.requests": "请求",
			"stats.sessions": "会话",
			"stats.in": "输入",
			"stats.out": "输出",
			"stats.cache": "缓存命中",
			"stats.model": "模型",
			"stats.less": "少",
			"stats.more": "多",
			"endpoint.note": "服务端点：{base}（改 endpoint 去设置文件）",
			"error.prefix": "出错："
		};

		var en = {
			"nav": "OpenCode Go",
			"section.title": "OpenCode Go settings",
			"key.title": "API key",
			"key.configured": "Configured (server-side, never echoed)",
			"key.missing": "Missing",
			"key.placeholder": "sk-…",
			"key.save": "Save key",
			"key.clear": "Clear",
			"key.empty": "Enter a key",
			"key.saved": "Saved",
			"models.title": "Models",
			"models.refresh": "Refresh catalog",
			"models.selectAll": "Select all",
			"models.selectNone": "Select none",
			"models.ctxPh": "context",
			"models.maxPh": "max out",
			"models.hint": "Refresh pulls the live model list from the server; only checked models appear in the picker.",
			"models.surfaces": "All three surfaces (chat / responses / messages) work; tags mark non-chat models.",
			"models.enabled": "{count} selected",
			"busy.key": "Saving…",
			"busy.models": "Refreshing…",
			"busy.stats": "Loading stats…",
			"stats.title": "Usage",
			"stats.tabOverview": "Overview",
			"stats.tabModels": "Models",
			"stats.total": "Total",
			"stats.tokens": "tokens",
			"stats.calls": "calls",
			"stats.colRequests": "requests",
			"stats.colIO": "in/out",
			"stats.colCache": "cache",
			"stats.refresh": "Refresh stats",
			"stats.reset": "Clear records",
			"stats.confirm": "Clear usage records? The current ledger is archived first.",
			"stats.empty": "No usage yet — go chat first.",
			"stats.requests": "requests",
			"stats.sessions": "sessions",
			"stats.in": "in",
			"stats.out": "out",
			"stats.cache": "cache hit",
			"stats.model": "model",
			"stats.less": "Less",
			"stats.more": "More",
			"endpoint.note": "Endpoint: {base} (change it in the settings file)",
			"error.prefix": "Error: "
		};
